#!/usr/bin/env python3
# 
# This file is part of robotkernel_service_helper.
# 
# robotkernel_service_helper is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
# 
# robotkernel_service_helper is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public License
# along with robotkernel; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

import yaml
import os
import argparse
from collections import OrderedDict

# Definiere einen Loader, der OrderedDict verwendet
#def construct_ordered_mapping(loader, node):
#    loader.flatten_mapping(node)
#    return OrderedDict(loader.construct_pairs(node))
#
## Registriere den Loader
#yaml.add_constructor(
#    yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG,
#    construct_ordered_mapping
#)

parser = argparse.ArgumentParser(description='Generate service definition header.')
parser.add_argument('--out', type=str, help='output header file name for service defintions')
parser.add_argument('--indir', type=str, help='input directory with svc_def files')
parser.add_argument('sd_files', metavar='svc_def', type=str, nargs='+',
                    help='yaml service definition files')
parser.add_argument('--name', type=str, help='base service definition name')
parser.add_argument('--add_namespace', type=str, help='additional base namespace')
parser.add_argument('--create-hdr-src-pair', dest='create_hdr_src_pair', action='store_true', help='Enable the feature')
parser.add_argument('--no-create-hdr-src-pair', dest='create_hdr_src_pair', action='store_false', help='Disable the feature')
parser.set_defaults(create_hdr_src_pair=False)

args = parser.parse_args()

print('rk_generate: writing output to %s' % args.out)

import random
import string

from string import Template

types = {}
bases = {}
pds = {}

builtin_dtypes = [ 
    'bool',
    'uint8_t',
    'uint16_t',
    'uint32_t',
    'uint64_t',
    'int8_t',
    'int16_t',
    'int32_t',
    'int64_t',
    'float',
    'double',
    'string' ]

def is_builtin(dtype):
    return dtype in builtin_dtypes

def decode_name(inname):
    name = inname
    namespaces = []
    if '/' in inname:
        parts = inname.split('/')
        name = parts[-1]
        namespaces = parts[:-1]

    return (name, namespaces)

def yaml_to_cpp_string(data, indent="    "):
    tmp = []
    inputlines = yaml.dump(data, sort_keys=False).split('\n')
    for line in inputlines:
        if line != "":
            line = line.replace('\\', '\\\\').replace('"', '\\"')
            tmp.append(f'{indent}"{line}\\n"')
    return '\n'.join(tmp)

def to_uint16_vector_lambda(indent):
    return f'''
{indent}// Conversion std::vector<uint8_t> → std::vector<uint16_t>
{indent}auto to_uint16_vector = [](const std::vector<uint8_t>& input) -> std::vector<uint16_t> {{
{indent}    std::vector<uint16_t> output;
{indent}    output.reserve(input.size());
{indent}    std::transform(input.begin(), input.end(), std::back_inserter(output),
{indent}                   [](uint8_t b) {{ return static_cast<uint16_t>(b); }});
{indent}    return output;
{indent}}};
'''

def from_uint16_vector_lambda(indent):
    return f'''
{indent}// Umwandlung: std::vector<uint16_t> → std::vector<uint8_t>
{indent}auto from_uint16_vector = [](const std::vector<uint16_t>& input) -> std::vector<uint8_t> {{
{indent}    std::vector<uint8_t> output;
{indent}    output.reserve(input.size());
{indent}
{indent}    std::transform(input.begin(), input.end(), std::back_inserter(output),
{indent}                   [](uint16_t word) {{
{indent}                       return static_cast<uint8_t>(word & 0xFF);  // nur unteres Byte
{indent}                   }});
{indent}
{indent}    return output;
{indent}}};
'''


class entry():
    def __init__(self, name, node):
        self.name = name
        self.type = node["type"]
        self.yaml_type = self.type if self.type != "uint8_t" else "uint16_t"
        self.array = node["array"] if "array" in node else False
        self.size = node["size"] if "size" in node else -1
        self.default = node["default"] if "default" in node else None

        if "bitfield" in node:
            self.bitfield = [ (n, e["bitsize"]) for n, e in node["bitfield"].items() ]

class dtype():
    def __init__(self, name, node):
        self.name = name
        self.real_name, self.namespaces = decode_name(self.name)
        self.fields = [ entry(n, e) for n, e in node["fields"].items() ]
        self.node = node

    def create_struct(self):
        fields = []
        for f in self.fields:
            if hasattr(f, "bitfield"):
                fields.append(f'    union {{')
                fields.append(f'        {decode_datatype(f, True)};')
                fields.append(f'        struct {{')
                for bf in f.bitfield:
                    bf_name, bf_bitsize = bf
                    fields.append(f'            {decode_datatype(f)} {bf_name} : {bf_bitsize};')
                fields.append(f'        }};')
                fields.append(f'    }};')
            else:
                fields.append(f'    {decode_datatype(f, True)};')
        fields = "\n".join(fields)
        namespaces_open = "\n".join(f'namespace {n} {{' for n in self.namespaces)
        namespaces_close= "\n".join(f'}}; // namespace {n}' for n in self.namespaces)

        return f'''
{namespaces_open}

//! datatype definition for {self.real_name}
static const std::string {self.real_name}_datatype_definition =
{yaml_to_cpp_string(self.node)};

//! data type structure for {self.real_name}
typedef struct {{
{fields}
}} {self.real_name};

{namespaces_close}
'''

    def create_yaml_coverters(self):
        need_lambdas = False
        encode_lines = []
        decode_lines = []
        for f in self.fields:
            if f.type == 'uint8_t' and f.array and f.size <= 0:
                encode_lines.append(f'            node["{f.name}"] = to_uint16_vector(rhs.{f.name});')
                decode_lines.append(f'            rhs.{f.name} = from_uint16_vector(node["{f.name}"].as<std::vector<uint16_t>>();')
                need_lambdas = True
            #elif hasattr(f, "bitfield"):

            else:
                if f.array and f.size > 0:
                    encode_lines.append(f'            std::array<{f.type}, {f.size}> arr;');
                    encode_lines.append(f'            memcpy(&arr[0], &rhs.{f.name}[0], {f.size} * sizeof({f.type}));')
                    encode_lines.append(f'            node["values"] = arr;')

                    decode_lines.append(f'            std::array<{f.type}, {f.size}> arr = node["{f.name}"].as<std::array<{f.type}, {f.size}>>();')
                    decode_lines.append(f'            memcpy(&rhs.{f.name}[0], &arr[0], {f.size} * sizeof({f.type}));')
                else:
                    encode_lines.append(f'            node["{f.name}"] = static_cast<const {decode_datatype(f, yaml_use=True)}>(rhs.{f.name});')
                    decode_lines.append(f'            rhs.{f.name} = node["{f.name}"].as<{decode_datatype(f)}>();')

        encode     = "\n".join(encode_lines)
        decode     = "\n".join(decode_lines)
        validation = "\n".join(f'            if (!node["{f.name}"]) {{ return false; }}' for f in self.fields)
        typename   = "::".join(([args.add_namespace] if args.add_namespace else []) + self.namespaces + [self.real_name])

        return f'''
// Definiere die Konvertierung für Test
namespace YAML {{
    template<>
    struct convert<{typename}> {{
        static Node encode(const {typename}& rhs) {{
            Node node;
{to_uint16_vector_lambda("            ") if need_lambdas else ''}
{encode}
            return node;
        }}

        static bool decode(const Node& node, {typename}& rhs) {{
{from_uint16_vector_lambda("            ") if need_lambdas else ''}
{validation}
{decode}
            return true;
        }}
    }};
}};
'''

class pd_base():
    def __init__(self, name, node):
        self.node = node
        self.org_name = name
        self.name, self.namespaces = decode_name(name)
        print("got ", self.name, self.namespaces)
        self.fields = [ entry(n, e) for n, e in node.items() ]

    def create_class(self):
        namespaces_open = "\n".join(f'namespace {n} {{' for n in self.namespaces)
        namespaces_close= "\n".join(f'}}; // namespace {n}' for n in self.namespaces)
        pd_entries = "\n".join(f'          {decode_datatype(f, True)};' for f in self.fields)
        add_datatypes = []
        remove_datatypes = []

        for e in self.fields:
            def func(t):
                add_datatypes.append(f'            ::robotkernel::add_datatype_definition(\n'
                                     f'                "{t.name}",\n'
                                     f'                {"::".join(t.namespaces + [t.real_name])}_datatype_definition);')
                remove_datatypes.append(f'            ::robotkernel::remove_datatype_definition("{t.name}");')

            def add_recursive(tn):
                if not is_builtin(tn):
                    t = types[tn]
                    for e in t.fields:
                        add_recursive(e.type)
                    func(t)

            add_recursive(e.type)

        add_datatypes = "\n".join(add_datatypes)
        remove_datatypes = "\n".join(remove_datatypes)

        return f'''
{namespaces_open}

class pd_{self.name} {{
    public:
        //! pd definition for {self.name}
        static constexpr const char* definition_name =
            "{self.org_name}";

        //! pd definition for {self.name}
        static constexpr const char* definition =
{yaml_to_cpp_string(self.node, indent="            ")};

        //! pd data structure for {self.name}
        struct __attribute__((__packed__)) data {{
{pd_entries}
        }};

        //! pd data structure size for {self.name}
        static constexpr size_t size = sizeof(struct data);

    private:
        // prevent creation and copying
        pd_{self.name}() = delete;
        pd_{self.name}(const pd_{self.name}&) = delete;
        pd_{self.name}& operator=(const pd_{self.name}&) = delete;
        pd_{self.name}(pd_{self.name}&&) = delete;
        pd_{self.name}& operator=(pd_{self.name}&&) = delete;
        ~pd_{self.name}() = delete;

    public:
        static void register_definition(void) {{
{add_datatypes}
            robotkernel::add_pd_definition(definition_name, definition);
        }}

        static void remove_definition(void) {{
            robotkernel::remove_pd_definition(definition_name);
{remove_datatypes}
        }}
}};

{namespaces_close}
'''

class svc_base():
    def __init__(self, name, node):
        self.node = node 
        self.org_name = name
        self.name, self.namespaces = decode_name(name)
        self.request = [ entry(n, e) for n, e in node["request"].items() ] if node is not None and "request" in node and node["request"] else []
        self.response = [ entry(n, e) for n, e in node["response"].items() ] if node is not None and "response" in node and node["response"] else []

    def create_class(self):
        request_entries = "\n".join(f'    {decode_datatype(f, True)};' for f in self.request)
        response_entries = "\n".join(f'    {decode_datatype(f, True)};' for f in self.response)
        namespaces_open = "\n".join(f'namespace {n} {{' for n in self.namespaces)
        namespaces_close= "\n".join(f'}}; // namespace {n}' for n in self.namespaces)
        init_request = []
        init_response = []
        parse_response = []
        need_from_lambda = False
        need_to_lambda = False

        for e in self.request:
            if e.type == 'uint8_t' and e.array:
                if e.size > 0:
                    parse_response.append(f'#error CASE request uint8_t and array not handled in line rk_generate')
                else:
                    init_request.append(f'            local_req.{e.name} = from_uint16_vector(::robotkernel::helpers::get_as'
                                        f'<{decode_datatype(e, yaml_use=True)}>(req, \"{e.name}\"));')
                need_from_lambda = True
            else:
                tmp_type = 'uint16_t' if e.type == 'uint8_t' else e.type
                if e.default is not None:
                    if e.type == 'uint8_t':
                        init_request.append(f'            local_req.{e.name} = ::robotkernel::helpers::get_as'
                                            f'<uint16_t>(req, "{e.name}", '
                                            f'{decode_default(tmp_type, e.default)});')
                    else:
                        init_request.append(f'            local_req.{e.name} = ::robotkernel::helpers::get_as'
                                            f'<{decode_datatype(e)}>(req, "{e.name}", '
                                            f'{decode_default(tmp_type, e.default)});')
                else:
                    if e.type == 'uint8_t':
                        init_request.append(f'            local_req.{e.name} = ::robotkernel::helpers::get_as'
                                        f'<uint16_t>(req, \"{e.name}\");')
                    else:
                        init_request.append(f'            local_req.{e.name} = ::robotkernel::helpers::get_as'
                                        f'<{decode_datatype(e)}>(req, \"{e.name}\");')

        for e in self.response:
            if e.default is not None:
                init_response.append(f'            local_resp.{e.name} = {decode_default(e.type, e.default)};')

        for e in self.response:
            if e.type == 'uint8_t' and e.array:
                if e.size > 0:
                    parse_response.append(f'#error CASE response uint8_t and array not handled in line rk_generate')
                else:
                    parse_response.append(f'            resp[\"{e.name}\"] = to_uint16_vector(local_resp.{e.name});')

                need_to_lambda = True
            else:
                if e.type == 'uint8_t':
                    parse_response.append(f'            resp[\"{e.name}\"] = static_cast<uint16_t>(local_resp.{e.name});')
                else:
                    parse_response.append(f'            resp[\"{e.name}\"] = static_cast<{decode_datatype(e, yaml_use=True)}>(local_resp.{e.name});')

        init_response = "\n".join(init_response)
        init_request = "\n".join(init_request)
        parse_response = "\n".join(parse_response)
        add_datatypes = []
        remove_datatypes = []

        for e in self.request + self.response:
            def func(t):
                add_datatypes.append(f'            ::robotkernel::add_datatype_definition(\n'
                                     f'                "{t.name}",\n'
                                     f'                {"::".join(t.namespaces + [t.real_name])}_datatype_definition);')
                remove_datatypes.append(f'            ::robotkernel::remove_datatype_definition("{t.name}");')

            def add_recursive(tn):
                if not is_builtin(tn):
                    t = types[tn]
                    for e in t.fields:
                        add_recursive(e.type)
                    func(t)

            add_recursive(e.type)

        add_datatypes = "\n".join(add_datatypes)
        remove_datatypes = "\n".join(remove_datatypes)

        return f'''
{namespaces_open}

//! service definition for {self.name}
static const std::string {self.name}_service_definition = 
{yaml_to_cpp_string(self.node)};

//! service request data structure for {self.name}
struct svc_req_{self.name} {{
{request_entries}
}};

//! service response data structure for {self.name}
struct svc_resp_{self.name} {{
{response_entries}
}};

//! base service class for {self.name}
class svc_base_{self.name} {{
    private:
        //! internal service handler, this one is registered to robotkernel
        /*!
         * @param[in]   req     Service request yaml.
         * @param[out]  resp    Service response yaml.
         * @return 0
         */
        int svc_handler_{self.name}(const YAML::Node& req, YAML::Node& resp) {{
            struct svc_req_{self.name} local_req = {{}};
            struct svc_resp_{self.name} local_resp = {{}};

{from_uint16_vector_lambda("            ") if need_from_lambda else ''}
{init_request}
{to_uint16_vector_lambda("            ") if need_to_lambda else ''}
{init_response}

            svc_{self.name}(local_req, local_resp);

{parse_response}

            return 0;
        }}

        std::string local_owner,    //!< @brief local service owner
                    local_name;     //!< @brief local service name

    public:
        //! destruction, unregisters service
        virtual ~svc_base_{self.name}() {{
            try {{
                remove_svc_{self.name}();
            }} catch (const std::exception& e) {{
            }}
        }};

        //! svc_{self.name}
        /*!
         * @param[in]   req     Service request data.
         * @param[out]  resp    Service response data.
         */
        virtual void svc_{self.name}(
            const struct svc_req_{self.name}& req,
            struct svc_resp_{self.name}& resp) = 0;

        //! adding service to robotkernel service store
        /*!
         * @param[in]   owner   Owner of this service.
         * @param[in]   name    Unique name in 'owner' namespace.
         */
        void add_svc_{self.name}(std::string owner, std::string name) {{
            local_owner = owner;
            local_name = name;

{add_datatypes}

            ::robotkernel::add_service_definition(
                "{self.org_name}",
                {self.name}_service_definition);
            ::robotkernel::add_service(owner, name,
                "{self.org_name}",
                std::bind(&svc_base_{self.name}::svc_handler_{self.name},
                this, std::placeholders::_1, std::placeholders::_2));
        }}

        //! remove service from robotkernel service store
        void remove_svc_{self.name}(void) {{
            ::robotkernel::remove_service(local_owner, local_name);
            ::robotkernel::remove_service_definition("{self.org_name}");

{remove_datatypes}
        }}
}};

{namespaces_close}
'''

def get_random_string(length):
    # choose from all uppercase letter
    letters = string.ascii_uppercase
    result_str = ''.join(random.choice(letters) for i in range(length))
    return result_str

def create_header(fd, name):
    hdr = f'''//! robotkernel service deinition header
/*!
 * author: generated by service_generator. DO NOT EDIT!
 */

#include <unistd.h>
#include <string>
#include <vector>
#include <robotkernel/service.h>
'''
    fd.write(hdr)
    if not args.create_hdr_src_pair:
        fd.write(f'''#include "robotkernel/robotkernel.h"
#include "robotkernel/helpers.h"
''')

    hdr = f'''#ifndef {name.upper()}_SERVICE_DEFINITIONS__H
#define {name.upper()}_SERVICE_DEFINITIONS__H

#include <vector>
#include <cstdint>
#include <algorithm>
'''

#// Umwandlung: std::vector<uint8_t> → std::vector<uint16_t>
#inline std::vector<uint16_t> to_uint16_vector(const std::vector<uint8_t>& input) {{
#    std::vector<uint16_t> output;
#    output.reserve(input.size());
#    std::transform(input.begin(), input.end(), std::back_inserter(output),
#                   [](uint8_t b) {{ return static_cast<uint16_t>(b); }});
#    return output;
#}}
#
#// Umwandlung: std::vector<uint16_t> → std::vector<uint8_t>
#inline std::vector<uint8_t> from_uint16_vector(const std::vector<uint16_t>& input) {{
#    std::vector<uint8_t> output;
#    output.reserve(input.size());
#
#    std::transform(input.begin(), input.end(), std::back_inserter(output),
#                   [](uint16_t word) {{
#                       return static_cast<uint8_t>(word & 0xFF);  // nur unteres Byte
#                   }});
#
#    return output;
#}}

    fd.write(hdr)

def create_footer(fd, name):
    ftr = f'''

#endif /* {name.upper()}_SERVICE_DEFINITIONS__H */

'''

    fd.write(ftr)

def is_primitive(datatype):
    if datatype == "string":
        return False

    return True

def decode_datatype(elem, with_name=False, yaml_use=False):
    dtype = elem.type if not yaml_use else elem.yaml_type

    if not is_builtin(dtype):
        real_dtype = types[dtype]
        dtype = "::".join(([args.add_namespace] if args.add_namespace else []) + real_dtype.namespaces + [real_dtype.real_name])

    if dtype == "string":
        dtype = "std::string"

    if elem.array:
        if elem.size > 0:
            dtype = f'{dtype} {elem.name}[{elem.size}]' if with_name else f'{dtype}[{elem.size}]'
        else:
            dtype = f'std::vector<{dtype}> {elem.name}' if with_name else f'std::vector<{dtype}>'
    else:
        dtype = f'{dtype} {elem.name}' if with_name else dtype

    return dtype

def decode_default(datatype, default):
    if datatype == "string":
        return f"\"{default}\""
    if datatype == "bool":
        return "true" if default else "false"

    return default

for fn in args.sd_files:
    sd = None
    sd_name = os.path.join(args.indir, fn)

    print("rk_generate: processing %s" % (sd_name))

    with open(sd_name, 'r') as stream:
        try:
            sd = yaml.load(stream, Loader=yaml.FullLoader)
        except:
            sd = yaml.load(stream)

    #print(yaml.dump(sd, default_flow_style=False, sort_keys=False))
    if "datatypes" in sd:
        for n, e in sd["datatypes"].items():
            tp = dtype(n, e)
            types[tp.name] = tp

    if "services" in sd:
        for n, e in sd["services"].items():
            tp = svc_base(n, e)
            bases[tp.org_name] = tp

    if "pds" in sd:
        for n, e in sd["pds"].items():
            tp = pd_base(n, e)
            pds[tp.org_name] = tp


outfd = open(args.out, 'w+')

prefix = args.name
if prefix is None:
    prefix = get_random_string(32)

create_header(outfd, prefix)

add_namespace = args.add_namespace
if add_namespace is not None:
    outfd.write(f'namespace {add_namespace} {{\n')

for name, dtype in types.items():
    outfd.write(dtype.create_struct())

if add_namespace is not None:
    outfd.write(f'\n\n}} // namespace {add_namespace}\n')

# YAML convert overloads must be outside of additional namespaace
for name, dtype in types.items():
    outfd.write(dtype.create_yaml_coverters())

if add_namespace is not None:
    outfd.write(f'namespace {add_namespace} {{\n')

for name, svc in bases.items():
    outfd.write(svc.create_class())

for name, pd in pds.items():
    print("processing ", name)
    outfd.write(pd.create_class())

if add_namespace is not None:
    outfd.write(f'\n\n}} // namespace {add_namespace}\n')

create_footer(outfd, prefix)

